### PR TITLE
Release 2.0.0-rc.1

### PR DESCRIPTION
**Pull request by fulldecent**
Release plan

- [ ] Complete review
- [ ] Merge to master
- [ ] Tag 2.0.0-rc.1
- [ ] Push NPM

---

Blockers for 2.0.0-rc.1: https://github.com/0xcert/ethereum-erc721/milestone/1

### CODE REVIEW

**Comment by fulldecent** [comment]
My review is complete. All blockers for 2.0.0-rc.1 identified and listed at https://github.com/0xcert/ethereum-erc721/milestone/1

Then READY TO SHIP.

**Comment by xpepermint** [comment]
@fulldecent I believe we are ready to merge this (and https://github.com/0xcert/ethereum-erc721/pull/182) to master and then publish the RC1.

**Comment by xpepermint** [comment]
This https://github.com/0xcert/ethereum-erc721/issues/165 is not a blocker. It will be done immediately after we merge this to `master` branch and before we publish the `npm` package.

**Comment by fulldecent** [comment]
I have reviewed this PR, everything looks good. 

Only exception is #183, let's review that and then I am 👍 to merge.

**Comment by xpepermint** [comment]
Done. Ready to be merged.

**Comment by fulldecent** [comment]
Can release manager please tag the release commit?

**Pull request merged**
