### PR TITLE
Fix documentation in ERC721Receiver.

### PR DESCRIPTION
**Pull request by mg6maciej**

### CODE REVIEW

**Comment by mg6maciej** [comment]
@xpepermint I have made changes to draft EIP-721 https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md to clarify this. Please wait before accepting this, I will update this PR to match the text in the specification.

**Comment by xpepermint** [comment]
Sounds perfect!

**Comment by fulldecent** [comment]
@mg6maciej This part is good:

>     /// @param _from The address which previously owned the token.

This part is bad (not necessarily true):

> +   * Note: this is not equal to the address that triggered the transaction.

**Comment by mg6maciej** [comment]
Rebased on @MoMannn's PR #89 to avoid merge conflicts.

**Pull request merged**
