### PR TITLE
Bump solidity version to 0.5.2

### PR DESCRIPTION
**Pull request by fulldecent**
This replaces https://github.com/0xcert/ethereum-erc721/pull/187

Currently, this repo is unusable in Remix because Solidity is old

### CODE REVIEW

**Comment by fulldecent** [comment]
@MoMannn Thank you, updated

**Comment by fulldecent** [comment]
@MoMannn @xpepermint Requesting updated review please.

As current, it is not possible to use this project inside Remix IDE with default settings. This PR fixes it.

**Comment by MoMannn** [comment]
@fulldecent The tests are still failing. I think you need to upload the new package-lock.json after the merge (recreate it and upload it) but I'm not 100% sure.

**Comment by xpepermint** [comment]
@fulldecent status?

**Comment by fulldecent** [comment]
Added dependency for websocket. This seems to be a bug with web3 and/or specron specifically related to upgrading solc from 0.5.1 to 0.5.2.

**Comment by fulldecent** [comment]
Now build is passing ✅

**Pull request merged**
