### PR TITLE
Make tokenURI overridable.

### PR DESCRIPTION
**Pull request by MoMannn**

### CODE REVIEW

**Review by xpepermint — APPROVED** [review]

**Comment by xpepermint** [comment]
I think it's good and absolutely necessary. @fulldecent any comments?

**Comment by fulldecent** [comment]
This looks great (after tests added). But can the string function please be extracted to a string library.

**Comment by xpepermint** [comment]
I agree. Good to go.

**Comment by fulldecent** [comment]
Got it: this is a mock, not a test mock. Fair. Agreed.

**Pull request merged**
